CREATE TABLE IF NOT EXISTS BTC_USD_DATA (
	Number INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Price_USD INT NOT NULL,
	Market_Capitalization_USD INT NOT NULL,
	Date_Stamp DATE,
)  ENGINE=INNODB;
